- name: Crear symlink para Prefect CLI
  file:
    src: /home/debian/.venv_prefect/bin/prefect
    dest: /usr/local/bin/prefect
    state: link

- name: Configurar PREFECT_API_URL
  shell: |
    prefect config set PREFECT_API_URL=http://{{ ansible_host }}:4200/api
  args:
    executable: /bin/bash

- name: Iniciar Prefect Server en background (systemd)
  become: true
  copy:
    dest: /etc/systemd/system/prefect.service
    content: |
      [Unit]
      Description=Prefect Server
      After=network.target

      [Service]
      User=debian
      Group=debian
      Type=simple
      WorkingDirectory=/home/{{ ansible_user }}
      Environment="PREFECT_API_URL=http://{{ ansible_host }}:4200/api"
      ExecStart=/home/debian/.venv_prefect/bin/prefect server start --host 0.0.0.0
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target

- name: Asegurar permisos correctos del entorno virtual
  become: true
  file:
    path: /home/debian/.venv_prefect
    state: directory
    recurse: yes
    owner: debian
    group: debian

- name: Recargar systemd y habilitar Prefect Server
  become: true
  systemd:
    daemon_reload: true
    name: prefect
    enabled: true
    state: started

- name: Ver solo PREFECT_API_URL desde systemd service
  shell: |
    systemctl show -p Environment prefect | grep PREFECT_API_URL
  register: api_env_check

- debug:
    msg: "Valor desde service file: {{ api_env_check.stdout }}"


#sudo journalctl -u prefect.service -f