- name: Instalar Prefect y dependencias
  import_tasks: install.yml

- name: Configurar Prefect
  import_tasks: config.yml

- name: Configurar Prefect Worker
  import_tasks: worker.yml

- name: Desplegar deployment Prefect Worker
  import_tasks: scripts.yml
