- name: Copiar directorio de Prefect
  copy:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/"
    dest: "{{ project_path }}/"
    owner: debian
    group: debian
    mode: '0755'
    directory_mode: '0755'

- name: Aplicar deployment YAML de Prefect
  shell: |
    source {{ venv_path }}/bin/activate
    prefect deployments apply {{ project_path }}/deployments/hello_deploy.yaml
  args:
    executable: /bin/bash
