- name: Copiar directorio de Prefect
  copy:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/"
    dest: "{{ project_path }}/"
    owner: debian
    group: debian
    mode: '0755'
    directory_mode: '0755'

- name: Configurar PREFECT_API_URL
  shell: |
    source /home/debian/.venv_prefect/bin/activate
    prefect config set PREFECT_API_URL=http://{{ ansible_host }}:4200/api
  args:
    executable: /bin/bash

- name: Validar PREFECT_API_URL y configuración de Prefect
  shell: |
    source /home/debian/.venv_prefect/bin/activate
    prefect config view
  args:
    executable: /bin/bash
  register: prefect_config

- name: Ejecutar flujo Prefect 3 con serve()
  ansible.builtin.shell: |
    source /home/debian/.venv_prefect/bin/activate
    cd /home/debian/prefect_project
    python3 flows/hello_flow.py
  args:
    executable: /bin/bash
  register: flow_output

- name: Mostrar resultado
  ansible.builtin.debug:
    var: flow_output.stdout_lines
