- name: Copiar directorio de Prefect
  copy:
    src: /iac_gcp_prefect/prefect/
    dest: "{{ project_path }}/"
    owner: debian
    group: debian
    mode: '0755'
    directory_mode: '0755'



- name: Construir deployment YAML
  shell: |
    source {{ venv_path }}/bin/activate
    cd {{ project_path }}
    prefect deployment build {{ flow_script }}:{{ flow_name }} \
      -n {{ deployment_name }} \
      -q {{ work_pool }} \
      --apply
  args:
    executable: /bin/bash