- name: Copiar directorio de Prefect
  copy:
    src: "{{ lookup('env', 'PROJECT_PATH') }}/"
    dest: "{{ project_path }}/"
    owner: debian
    group: debian
    mode: '0755'
    directory_mode: '0755'

- name: Configurar PREFECT_API_URL
  shell: |
    source /home/debian/.venv_prefect/bin/activate
    prefect config set PREFECT_API_URL=http://{{ ansible_host }}:4200/api
  args:
    executable: /bin/bash

- name: Validar PREFECT_API_URL y configuración de Prefect
  shell: |
    source /home/debian/.venv_prefect/bin/activate
    prefect config view
  args:
    executable: /bin/bash
  register: prefect_config

- name: Agregar host dinámico al /etc/hosts
  hosts: all
  become: yes
  tasks:
    - name: Asegurar que la IP y hostname estén en /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} database_postgres"
        state: present

- name: Ejecutar flujo Prefect 3 
  ansible.builtin.shell: |
    source /home/debian/.venv_prefect/bin/activate
    prefect config set PREFECT_API_URL=http://{{ ansible_host }}:4200/api
    cd /home/debian/prefect_project/flows
    pip3 install -r requirements.txt
    python3 hello_world.py
  args:
    executable: /bin/bash
  register: flow_output

- name: Mostrar resultado
  ansible.builtin.debug:
    var: flow_output.stdout_lines
