- name: Instalar PostgreSQL
  hosts: postgresql
  become: true
  vars:
    ansible_user: debian
  roles:
    - postgresql


- name: Instalar Prefect
  hosts: prefect
  become: true
  roles:
    - prefect