- name: DEBUG - Mostrar variable postgresql_version
  debug:
    msg: "Versión de PostgreSQL: {{ postgresql_version }}"

- name: Guardar IP como variable global de play
  set_fact:
    postgres_ip: "{{ postgresql_listen_addresses}}"

- name: Instalar PostgreSQL y dependencias
  import_tasks: install.yml

- name: Configurar PostgreSQL
  import_tasks: config.yml

- name: Crear bases de datos
  import_tasks: databases.yml

- name: Crear usuarios
  import_tasks: users.yml

- name: Ejecutar script
  import_tasks: scripts.yml